version: '3.8'
volumes:
  postgres_volume:
    name: ${POSTGRES_VOLUME_NAME}
services:
  postgis:
    image: bde2020/postgis
    hostname: postgis
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    volumes:
      - postgres_volume:/var/lib/postgresql/9.4/main:rw
    ports:
      - ${POSTGRES_PORT}:5432
  strabon:
    build:
      context: https://github.com/VCityTeam/Strabon-CORS-Docker.git
      args:
        - STRABON_USERNAME=${STRABON_USERNAME}
        - STRABON_PASSWORD=${STRABON_PASSWORD}
    image: vcity/strabon-cors
    hostname: strabon
    environment:
      - STRABON_CONNECTION_hostname=${POSTGRES_ORDBMS}
      - STRABON_CONNECTION_port=${POSTGRES_PORT}
    ports:
      - ${STRABON_PORT}:8080
  udviz:
    build:
      context: ./ud-viz-context
    ports:
      - ${UD_VIZ_PORT}:8998