PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX geo:    <http://www.opengis.net/ont/geosparql#>
PREFIX core: <https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/2.0/core#>
PREFIX bldg: <https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/2.0/building#>
PREFIX v2009: <https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Datasets/2009/GratteCiel_2009_split#>
PREFIX v2012: <https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Datasets/2012/GratteCiel_2012_split#>
PREFIX v2015: <https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Datasets/2015/GratteCiel_2015_split#>
PREFIX v2018: <https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Datasets/2018/GratteCiel_2018_split#>


# return a Building matching an URI

SELECT ?subject ?subjectType ?predicate ?object ?objectType
WHERE {
  {
    ?subject ?predicate ?object ;
      a ?subjectType ;
    OPTIONAL { ?object a ?objectType }
    FILTER ( v2015:BU_69266BC39_1 = ?subject )  
  } UNION {
    v2015:BU_69266BC39_1 bldg:AbstractBuilding.boundedBy ?subject .
    ?subject ?predicate ?object ;
      a ?subjectType .
    OPTIONAL { ?object a ?objectType }
  
  } UNION {
    v2015:BU_69266BC39_1 bldg:AbstractBuilding.boundedBy/geo:hasGeometry ?subject .
    ?subject ?predicate ?object ;
      a ?subjectType .
    OPTIONAL { ?object a ?objectType }
  
  }
  FILTER(?subjectType != owl:NamedIndividual)
  FILTER(?objectType != owl:NamedIndividual)
}
