FROM bde2020/strabon

# Enable CORS support and connection/credential properties for Strabon/tomcat frontend 
COPY web.xml /tomcat/conf/web.xml
COPY credentials.properties /tomcat/webapps/strabon/WEB-INF/credentials.properties